### ISSUE TITLE
Can't run IDLE after enabling win-unicode-console

### ISSUE THREAD

**Issue by 5j9** [Drekin/win-unicode-console#33]
As soon as I put
```python
import win_unicode_console


win_unicode_console.enable()

```
in `sitecustomize.py`, IDLE won't run anymore (without showing any error message).

If I comment out the `#win_unicode_console.enable()` function call (only keeping the import statement) IDLE works again.

If I open an IDLE shell, reenable the `win_unicode_console.enable()`, then try to restart the shell, the following error shows up:

> ---------------------------
> Subprocess Startup Error
> ---------------------------
> IDLE's subprocess didn't make connection.  Either IDLE can't start a subprocess or personal firewall software is blocking the connection.
> ---------------------------
> OK   
> ---------------------------

I'm running
* Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
* Windows 10 64-bit
* win-unicode-console (0.5)

Does anyone know why this is happening?

**Comment by Drekin** [comment]
There is probably an exception in `sitecustomize`, but I don't know how to read the traceback when the application is GUI (i.e. run by `pyw`).

**Comment by Drekin** [comment]
This is a bug. Quick fix is to wrap `win_unicode_console.enable()` with `try:…; except Exception: pass`. I'll make a proper fix eventually.

**Comment by 5j9** [comment]
Thanks.

I guess you already have figured it out, but I had logged the exception before seeing you last comment:

to log the except I used `logging` in `sitecustomize`:
```
import win_unicode_console
import logging

logging.basicConfig(filename='pw_error.log',level=logging.DEBUG)

try:
    win_unicode_console.enable()
except Exception as e:
    logging.exception('Exception:')
```

And here is the error log:
```
ERROR:root:Exception:
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python35\lib\site-packages\sitecustomize.py", line 7, in <module>
    win_unicode_console.enable()
  File "C:\Users\a\AppData\Local\Programs\Python\Python35\lib\site-packages\win_unicode_console\__init__.py", line 28, in enable
    streams.enable(stdin=stdin, stdout=stdout, stderr=stderr)
  File "C:\Users\a\AppData\Local\Programs\Python\Python35\lib\site-packages\win_unicode_console\streams.py", line 329, in enable
    sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
ERROR:root:Exception:
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python35\lib\site-packages\sitecustomize.py", line 7, in <module>
    win_unicode_console.enable()
  File "C:\Users\a\AppData\Local\Programs\Python\Python35\lib\site-packages\win_unicode_console\__init__.py", line 28, in enable
    streams.enable(stdin=stdin, stdout=stdout, stderr=stderr)
  File "C:\Users\a\AppData\Local\Programs\Python\Python35\lib\site-packages\win_unicode_console\streams.py", line 329, in enable
    sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
```

**Comment by Drekin** [comment]
Yes, this is one bug. Another one is that the detection mechanisms shouldn't enable the streams at all.

**Comment by eric-wieser** [comment]
Can you change the readme to include this `try except`? Lost some time diagnosing this

**Comment by Drekin** [comment]
@eric-wieser Even better would be to actually fix the bug, by detecting IDLE properly. :-)

**Comment by eric-wieser** [comment]
@Drekin: Seems that it might just be that `pythonw` fails generally
