### ISSUE TITLE
Error installing package under Python2

### ISSUE THREAD

**Issue by thorstenkampe** [Drekin/win-unicode-console#6]
```
thorsten@rednails[F:\...\script] tcc> pip2 install win-unicode-console
Collecting win-unicode-console
  Using cached win_unicode_console-0.3.1.zip
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\thorsten\appdata\local\temp\pip-build-pcloii\win-unicode-console\setup.py", line 30, in <module>
        long_description=read(README),
      File "c:\users\thorsten\appdata\local\temp\pip-build-pcloii\win-unicode-console\setup.py", line 9, in read
        with open(path.join(HERE, *relative_path_parts), encoding=ENCODING) as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "c:\users\thorsten\appdata\local\temp\pip-build-pcloii\win-unicode-console\setup.py", line 30, in <module>

        long_description=read(README),

      File "c:\users\thorsten\appdata\local\temp\pip-build-pcloii\win-unicode-console\setup.py", line 9, in read

        with open(path.join(HERE, *relative_path_parts), encoding=ENCODING) as f:

    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in c:\users\thorsten\appdata\local\temp\pip-build-pcloii\win-unicode-console
```

**Comment by Drekin** [comment]
Python 2 is currently not supported, so there is no use in installing the package on Python 2. Maybe, an explicit note that Python 2 is not supported could be added. I'm merging this issue with #7.
